name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: Build with Maven
    #  run: mvn -B -DskipTests clean package
      
    - name: Build Node.js Application
      run: |
        cd result
        npm install
        npm run build  # Or any other build command for your Node.js app
        
    - name: Build the Docker image
      run: docker build . --file vote/Dockerfile --tag my-image-name:$(date +%s)

    - name: Package Helm Chart
      run: helm package path/to/your/helm/chart  
